// Fixed disposable PostgreSQL only. No dotenv, provider keys or live model calls.
const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
for(const key of Object.keys(process.env))if(/API_KEY|DATABASE_URL|JWT_SECRET/.test(key))delete process.env[key];
Object.assign(process.env,{DATABASE_URL:'postgresql://postgres:buildx-test-only@127.0.0.1:55439/buildx_test',ALLOW_DB_FALLBACK:'false',JWT_SECRET:'queue-test-only-secret',NODE_ENV:'test',AGENT_QUEUE_ENABLED:'true'});
const db=require('../dist/lib/db');
const {revision}=require('../dist/lib/agent/validation');
let workspace;
require('../dist/lib/agent/engine').runEngineeringAgent=async(prompt,files,options)=>{
 await options.checkpoint({synthetic:true});
 if(prompt==='concurrent edit')await db.saveBlueprintFile(workspace,'main.ts','newer edit','typescript');
 return {message:'Synthetic candidate',revision:revision(Object.fromEntries(files.map(f=>[f.path,f.content]))),modifiedFiles:[{path:'main.ts',content:'candidate'}],stagedDiffs:{'main.ts':{original:'original',modified:'candidate'}}};
};
const {queuedWorkspaceHandler}=require('../dist/lib/agent/queued-workspace');
const {AgentQueue}=require('../dist/lib/agent/queue');
const {workOnce}=require('../dist/lib/agent/worker');
const jwt=require('jsonwebtoken');
let server,pool,base;
async function request(path,method='GET',body,token){return fetch(base+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body===undefined?undefined:JSON.stringify(body)});}
(async()=>{
 const owner=await db.createUser('Queue test',randomUUID()+'@example.test','unused-test-hash');
 const fixture=require('./fixtures/blueprint.json');
 workspace=await db.saveBlueprint('queue fixture',fixture,owner);
 await db.saveBlueprintFile(workspace,'main.ts','original','typescript');
 pool=await db.getAgentPool();const queue=new AgentQueue(pool);await queue.initialize();
 server=require('../dist/app').default.listen(0,'127.0.0.1');
 await new Promise((resolve,reject)=>{server.once('listening',resolve);server.once('error',reject);});
 base='http://127.0.0.1:'+server.address().port;
 const token=jwt.sign({userId:owner,email:'test@example.test'},process.env.JWT_SECRET);
 const other=jwt.sign({userId:randomUUID(),email:'other@example.test'},process.env.JWT_SECRET);
 const endpoint='/api/agent/'+workspace+'/jobs';
 const input={key:randomUUID(),kind:'chat',prompt:'normal'};
 assert.equal((await request(endpoint,'POST',input)).status,401);
 process.env.AGENT_QUEUE_ENABLED='false';assert.equal((await request(endpoint,'POST',input,token)).status,503);process.env.AGENT_QUEUE_ENABLED='true';
 assert.equal((await request(endpoint,'POST',input,other)).status,404);
 assert.equal((await request(endpoint,'POST',{...input,prompt:''},token)).status,400);
 assert.equal((await request(endpoint,'POST',{...input,model:'invalid-model'},token)).status,400);
 const response=await request(endpoint,'POST',input,token);assert.equal(response.status,202);const job=await response.json();
 assert.equal((await (await request(endpoint,'POST',input,token)).json()).jobId,job.jobId);
 assert.equal((await request(endpoint,'POST',{...input,prompt:'changed'},token)).status,409);
 assert.equal((await request(endpoint+'/'+job.jobId,'GET',undefined,other)).status,404);
 await workOnce(queue,{chat:queuedWorkspaceHandler},new AbortController().signal);
 const complete=await (await request(endpoint+'/'+job.jobId,'GET',undefined,token)).json();
 assert.equal(complete.status,'completed');assert.equal(complete.result.modifiedFiles[0].content,'candidate');assert.equal(complete.checkpoint,undefined);
 assert.equal((await db.getBlueprintFiles(workspace))[0].content,'original');
 const history=await (await request(endpoint,'GET',undefined,token)).json();
 assert.equal(history.runs[0].id,job.jobId);assert.equal(history.runs[0].checkpoint,undefined);
 assert.equal((await request(endpoint,'GET',undefined,other)).status,404);
 assert.equal((await db.getChatMessages(workspace,owner)).length,2);
 console.log('PASS: authenticated job API, flag, validation, ownership, idempotency, worker result polling and candidate isolation');
 const conflicting=await queue.enqueue({owner,workspace,key:randomUUID(),kind:'chat',payload:{prompt:'concurrent edit'}});
 await workOnce(queue,{chat:queuedWorkspaceHandler},new AbortController().signal);
 assert.equal((await db.getChatMessages(workspace,owner)).length,2);
 assert.equal((await queue.get(conflicting.id,owner)).status,'failed');assert.match((await queue.get(conflicting.id,owner)).error,/Workspace changed/);
 const cancelled=await (await request(endpoint,'POST',{...input,key:randomUUID()},token)).json();
 assert.equal((await request(endpoint+'/'+cancelled.jobId+'/cancel','POST',{},other)).status,404);
 assert.deepEqual(await (await request(endpoint+'/'+cancelled.jobId+'/cancel','POST',{},token)).json(),{cancelled:true});
 assert.equal((await queue.get(cancelled.jobId,owner)).status,'cancelled');
 const empty=await db.saveBlueprint('empty queue fixture',fixture,owner);
 const generated=await queue.enqueue({owner,workspace:empty,key:randomUUID(),kind:'codegen',payload:{prompt:'normal'}});
 await workOnce(queue,{codegen:queuedWorkspaceHandler},new AbortController().signal);
 const result=await queue.get(generated.id,owner);assert.equal(result.status,'completed',result.error);
 assert.ok(result.result.modifiedFiles.length>10);assert.equal(result.result.revision,revision({}));
 assert.ok(Object.values(result.result.stagedDiffs).every(diff=>diff.original===''));
 assert.equal((await db.getBlueprintFiles(empty)).length,0);
 console.log('PASS: stale-workspace rejection, HTTP cancellation, complete scaffold staged without applying files');
 const waiting=await (await request(endpoint,'POST',{...input,key:randomUUID(),prompt:'Wait for capacity'},token)).json();
 await workOnce(queue,{chat:async()=>{throw Object.assign(new Error('Synthetic provider overload'),{status:503});}},new AbortController().signal);
 const waitingSnapshot=await (await request(endpoint+'/'+waiting.jobId,'GET',undefined,token)).json();
 assert.equal(waitingSnapshot.status,'queued');assert.equal(waitingSnapshot.attempt,1);
 assert.ok(Date.parse(waitingSnapshot.nextAttemptAt)>Date.now());
 assert.equal(waitingSnapshot.error,'AI capacity is temporarily unavailable. Retrying automatically.');
 const waitingHistory=await (await request(endpoint,'GET',undefined,token)).json();
 assert.equal(waitingHistory.runs[0].id,waiting.jobId);
 assert.ok(Date.parse(waitingHistory.runs[0].nextAttemptAt)>Date.now());
 assert.equal(await queue.claim(),null);
 assert.deepEqual(await (await request(endpoint+'/'+waiting.jobId+'/cancel','POST',{},token)).json(),{cancelled:true});
 assert.equal((await queue.get(waiting.jobId,owner)).status,'cancelled');
 console.log('PASS: HTTP waiting state, retry deadline, history and cancellation');
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{
 if(server){server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}
 if(pool)await pool.end();
});
