import React, { useState } from 'react';
import { Terminal, Code2, Play, Github, Download, Check, Sparkles, Layers, ShieldCheck, Cpu } from 'lucide-react';

export function BentoGrid() {
  const [activeFileTab, setActiveFileTab] = useState<'app' | 'client' | 'schema'>('app');
  const [copied, setCopied] = useState(false);

  const fileContents = {
    app: `// backend/src/app.ts
import express from 'express';
import { router as apiRouter } from './routes';

export const app = express();
app.use(express.json());
app.use('/api/v1', apiRouter);`,
    client: `// frontend/src/api/client.ts
import axios from 'axios';

export const client = axios.create({
  baseURL: '/api/v1',
  headers: { 'Content-Type': 'application/json' }
});`,
    schema: `-- db/schema.sql
CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);`,
  };

  const copyCode = () => {
    navigator.clipboard.writeText(fileContents[activeFileTab]);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <section className="w-full max-w-6xl mx-auto px-4 py-20">
      <div className="text-center max-w-2xl mx-auto mb-16 space-y-4">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/[0.04] border border-white/10 text-xs font-medium text-neutral-300">
          <Layers size={13} className="text-indigo-400" />
          <span>Platform Architecture</span>
        </div>
        <h2 className="text-3xl md:text-4xl font-bold tracking-tight text-white">
          Production-ready from idea to deployment
        </h2>
        <p className="text-base text-neutral-400">
          Every blueprint generated by BuildX includes full-stack backend routers, database schemas, and frontend interfaces.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Card 1: Large Code Explorer (Spans 2 columns on desktop) */}
        <div className="md:col-span-2 rounded-2xl bg-neutral-900/60 border border-neutral-800 p-6 flex flex-col justify-between relative overflow-hidden group hover:border-neutral-700 transition-all duration-300">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2">
              <Code2 size={18} className="text-indigo-400" />
              <span className="text-sm font-semibold text-white">Interactive Codebase Explorer</span>
            </div>
            <button
              onClick={copyCode}
              className="px-2.5 py-1 rounded-lg bg-neutral-800 hover:bg-neutral-700 border border-neutral-700 text-xs text-neutral-300 flex items-center gap-1.5 transition-colors"
            >
              {copied ? <Check size={12} className="text-emerald-400" /> : null}
              <span>{copied ? 'Copied' : 'Copy Code'}</span>
            </button>
          </div>

          {/* File Tabs */}
          <div className="flex items-center gap-1 border-b border-neutral-800 pb-2 mb-3">
            {(['app', 'client', 'schema'] as const).map((tab) => (
              <button
                key={tab}
                onClick={() => setActiveFileTab(tab)}
                className={`px-3 py-1 rounded-md text-xs font-mono transition-colors ${
                  activeFileTab === tab
                    ? 'bg-white/10 text-white font-medium border border-white/10'
                    : 'text-neutral-500 hover:text-neutral-300'
                }`}
              >
                {tab === 'app' ? 'app.ts' : tab === 'client' ? 'client.ts' : 'schema.sql'}
              </button>
            ))}
          </div>

          {/* Syntax Highlighted Code Window */}
          <div className="bg-black/80 rounded-xl p-4 font-mono text-xs text-neutral-300 overflow-x-auto border border-neutral-800/80 shadow-inner">
            <pre className="leading-relaxed">{fileContents[activeFileTab]}</pre>
          </div>
        </div>

        {/* Card 2: Agent Reasoning Timeline */}
        <div className="rounded-2xl bg-neutral-900/60 border border-neutral-800 p-6 flex flex-col justify-between group hover:border-neutral-700 transition-all duration-300">
          <div>
            <div className="flex items-center gap-2 mb-4">
              <Sparkles size={18} className="text-emerald-400" />
              <span className="text-sm font-semibold text-white">Agentic Workflow</span>
            </div>
            <p className="text-xs text-neutral-400 mb-6 leading-relaxed">
              Real-time multi-step execution tracing each step from prompt evaluation to database migrations.
            </p>

            {/* Step List */}
            <div className="space-y-3 font-mono text-xs">
              <div className="flex items-center gap-2 text-emerald-400 bg-emerald-500/10 p-2 rounded-lg border border-emerald-500/20">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse"></span>
                <span>01. Parse blueprint prompt schema</span>
              </div>
              <div className="flex items-center gap-2 text-neutral-300 bg-neutral-800/40 p-2 rounded-lg border border-neutral-800">
                <Check size={12} className="text-emerald-400" />
                <span>02. Generate PostgreSQL models</span>
              </div>
              <div className="flex items-center gap-2 text-neutral-300 bg-neutral-800/40 p-2 rounded-lg border border-neutral-800">
                <Check size={12} className="text-emerald-400" />
                <span>03. Build Express REST endpoints</span>
              </div>
              <div className="flex items-center gap-2 text-neutral-400 bg-neutral-800/20 p-2 rounded-lg border border-neutral-800/50">
                <span className="w-1.5 h-1.5 rounded-full bg-neutral-600"></span>
                <span>04. Verify TypeScript compilation</span>
              </div>
            </div>
          </div>
        </div>

        {/* Card 3: Instant Sandbox */}
        <div className="rounded-2xl bg-neutral-900/60 border border-neutral-800 p-6 flex flex-col justify-between group hover:border-neutral-700 transition-all duration-300">
          <div>
            <div className="flex items-center gap-2 mb-3">
              <Play size={18} className="text-blue-400" />
              <span className="text-sm font-semibold text-white">Instant UI Preview</span>
            </div>
            <p className="text-xs text-neutral-400 leading-relaxed mb-4">
              Interactive sandbox rendering generated screens without local setup.
            </p>
          </div>
          <div className="p-3 bg-black/60 rounded-xl border border-neutral-800 text-center">
            <span className="text-xs font-mono text-neutral-400">100% Client-Side Transpilation</span>
          </div>
        </div>

        {/* Card 4: GitHub Export & Scaffolding (Spans 2 columns on desktop) */}
        <div className="md:col-span-2 rounded-2xl bg-neutral-900/60 border border-neutral-800 p-6 flex flex-col md:flex-row items-start md:items-center justify-between gap-6 group hover:border-neutral-700 transition-all duration-300">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <Github size={18} className="text-white" />
              <span className="text-sm font-semibold text-white">GitHub Sync & ZIP Export</span>
            </div>
            <p className="text-xs text-neutral-400 max-w-md leading-relaxed">
              Export full production repos directly to GitHub or download as a self-contained ZIP archive ready for `npm install`.
            </p>
          </div>
          <div className="flex items-center gap-3 w-full md:w-auto">
            <button className="flex-1 md:flex-initial px-4 py-2.5 rounded-xl bg-white hover:bg-neutral-200 text-black text-xs font-semibold flex items-center justify-center gap-2 transition-colors">
              <Github size={14} />
              <span>Push to GitHub</span>
            </button>
            <button className="flex-1 md:flex-initial px-4 py-2.5 rounded-xl bg-neutral-800 hover:bg-neutral-700 border border-neutral-700 text-white text-xs font-medium flex items-center justify-center gap-2 transition-colors">
              <Download size={14} />
              <span>Download ZIP</span>
            </button>
          </div>
        </div>
      </div>
    </section>
  );
}
