import type { Blueprint } from '../lib/types';
import { generateMonorepoFiles } from '../lib/scaffold';

/**
 * Returns the language mode for a file path based on its extension.
 */
export function getLanguageFromPath(filePath: string): string {
  const ext = filePath.split('.').pop()?.toLowerCase() ?? '';
  switch (ext) {
    case 'ts':
    case 'tsx':
      return 'typescript';
    case 'js':
    case 'jsx':
      return 'javascript';
    case 'json':
      return 'json';
    case 'sql':
      return 'sql';
    case 'md':
      return 'markdown';
    case 'html':
      return 'html';
    case 'css':
      return 'css';
    case 'yml':
    case 'yaml':
      return 'yaml';
    case 'prisma':
      return 'prisma';
    case 'env':
    case 'example':
      return 'shell';
    default:
      return 'plaintext';
  }
}

/**
 * Generates a Virtual File System (VFS) dictionary (filePath -> fileContent)
 * from a Blueprint specification object.
 */
export function generateVFSFromBlueprint(blueprintSpec: Blueprint): Record<string, string> {
  if (!blueprintSpec) {
    throw new Error('Blueprint specification is required to generate VFS');
  }

  // Generate standard monorepo scaffold files using BuildX scaffold generator
  const files = generateMonorepoFiles(blueprintSpec);

  // Ensure critical scaffold files are present
  if (!files['package.json']) {
    files['package.json'] = JSON.stringify(
      {
        name: (blueprintSpec.appName || 'buildx-app').toLowerCase().replace(/\s+/g, '-'),
        version: '1.0.0',
        private: true,
        scripts: {
          dev: 'concurrently "npm run dev:backend" "npm run dev:frontend"',
        },
      },
      null,
      2
    );
  }

  if (!files['tsconfig.json']) {
    files['tsconfig.json'] = JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          module: 'NodeNext',
          moduleResolution: 'NodeNext',
          esModuleInterop: true,
          strict: true,
        },
      },
      null,
      2
    );
  }

  if (!files['README.md']) {
    files['README.md'] = `# ${blueprintSpec.appName}\n\n${blueprintSpec.description}\n\nGenerated by BuildX AI Architect.\n`;
  }

  return files;
}
