import archiver from 'archiver';
import { Response } from 'express';
import type { Blueprint } from './types';

// ─── Helpers ───────────────────────────────────────────────

function toSnakeCase(str: string): string {
  return str
    .replace(/([a-z])([A-Z])/g, '$1_$2')
    .replace(/[\s\-]+/g, '_')
    .toLowerCase();
}

function toKebabCase(str: string): string {
  return str
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase();
}

function toPascalCase(str: string): string {
  return str
    .replace(/[\s_\-]+(.)/g, (_, c) => c.toUpperCase())
    .replace(/^(.)/, (_, c) => c.toUpperCase());
}

function toCamelCase(str: string): string {
  const pascal = toPascalCase(str);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

/** Map SQL types to Prisma scalar types */
function sqlTypeToPrisma(sqlType: string): string {
  const t = sqlType.toUpperCase();
  if (t.includes('UUID')) return 'String @default(uuid())';
  if (t.includes('SERIAL') || t.includes('BIGSERIAL')) return 'Int @default(autoincrement())';
  if (t.includes('INT')) return 'Int';
  if (t.includes('FLOAT') || t.includes('DOUBLE') || t.includes('DECIMAL') || t.includes('NUMERIC'))
    return 'Float';
  if (t.includes('BOOL')) return 'Boolean';
  if (t.includes('TIMESTAMP') || t.includes('DATE')) return 'DateTime';
  if (t.includes('JSON')) return 'Json';
  if (t.includes('TEXT')) return 'String';
  if (t.includes('VARCHAR')) return 'String';
  return 'String';
}

function isPrimaryKey(col: { name: string; type: string; note?: string }): boolean {
  const t = (col.type + ' ' + (col.note || '')).toUpperCase();
  return t.includes('PRIMARY KEY') || t.includes('PK');
}

function hasDefault(type: string): boolean {
  return type.toUpperCase().includes('DEFAULT');
}

// ─── File generators ───────────────────────────────────────

function generateRootPackageJson(bp: Blueprint): string {
  const name = toKebabCase(bp.appName);
  return JSON.stringify(
    {
      name,
      version: '0.1.0',
      private: true,
      description: bp.description,
      scripts: {
        'dev:backend': 'cd backend && npm run dev',
        'dev:frontend': 'cd frontend && npm run dev',
        dev: 'concurrently "npm run dev:backend" "npm run dev:frontend"',
        install: 'cd backend && npm install && cd ../frontend && npm install',
      },
      devDependencies: {
        concurrently: '^8.2.2',
      },
    },
    null,
    2
  );
}

function generateBackendPackageJson(bp: Blueprint): string {
  const name = toKebabCase(bp.appName) + '-backend';
  return JSON.stringify(
    {
      name,
      version: '0.1.0',
      private: true,
      scripts: {
        dev: 'ts-node-dev --respawn --transpile-only src/index.ts',
        build: 'tsc',
        start: 'node dist/index.js',
      },
      dependencies: {
        '@prisma/client': '^5.7.0',
        cors: '^2.8.5',
        dotenv: '^16.3.1',
        express: '^4.18.2',
        helmet: '^7.1.0',
        zod: '^3.22.4',
      },
      devDependencies: {
        '@types/cors': '^2.8.17',
        '@types/express': '^4.17.21',
        '@types/node': '^20.10.0',
        prisma: '^5.7.0',
        'ts-node-dev': '^2.0.0',
        typescript: '^5.3.2',
      },
    },
    null,
    2
  );
}

function generateBackendTsconfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2020',
        module: 'commonjs',
        lib: ['ES2020'],
        outDir: './dist',
        rootDir: './src',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
        resolveJsonModule: true,
        sourceMap: true,
      },
      include: ['src/**/*'],
      exclude: ['node_modules', 'dist'],
    },
    null,
    2
  );
}

function generatePrismaSchema(bp: Blueprint): string {
  let schema = `// Prisma schema generated by BuildX
// https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
`;

  for (const table of bp.schema) {
    const modelName = toPascalCase(table.table);
    schema += `\nmodel ${modelName} {\n`;

    for (const col of table.columns) {
      const fieldName = toCamelCase(col.name);
      let prismaType = sqlTypeToPrisma(col.type);

      // Handle primary key
      if (isPrimaryKey(col)) {
        prismaType = prismaType.includes('@default')
          ? prismaType + ' @id'
          : prismaType + ' @id @default(autoincrement())';
      }

      // Handle unique
      if (col.type.toUpperCase().includes('UNIQUE')) {
        prismaType += ' @unique';
      }

      // Handle NOT NULL — Prisma fields are required by default, add ? for nullable
      const isRequired = col.type.toUpperCase().includes('NOT NULL') || isPrimaryKey(col);
      const typeStr = isRequired ? prismaType : prismaType + '?';

      // Handle default timestamps
      if (col.type.toUpperCase().includes('DEFAULT NOW()') || col.type.toUpperCase().includes('DEFAULT CURRENT_TIMESTAMP')) {
        schema += `  ${fieldName.padEnd(20)} DateTime  @default(now())\n`;
      } else {
        schema += `  ${fieldName.padEnd(20)} ${typeStr}\n`;
      }
    }

    schema += '}\n';
  }

  return schema;
}

function generateBackendIndex(bp: Blueprint): string {
  return `import 'dotenv/config';
import app from './app';

const PORT = parseInt(process.env.PORT || '3001', 10);

app.listen(PORT, () => {
  console.log(\`\\n⚡ ${bp.appName} API running on http://localhost:\${PORT}\`);
  console.log(\`   ENV: \${process.env.NODE_ENV || 'development'}\\n\`);
});
`;
}

function generateBackendApp(bp: Blueprint): string {
  // Collect unique resource names from endpoints
  const resources = new Set<string>();
  for (const ep of bp.endpoints) {
    const parts = ep.path.split('/').filter(Boolean);
    // e.g. /api/auth/login → auth, /api/products → products
    if (parts.length >= 2) {
      resources.add(parts[1]);
    }
  }

  const imports = Array.from(resources)
    .map((r) => `import ${toCamelCase(r)}Router from './routes/${r}';`)
    .join('\n');

  const routes = Array.from(resources)
    .map((r) => `app.use('/api/${r}', ${toCamelCase(r)}Router);`)
    .join('\n');

  return `import express from 'express';
import cors from 'cors';
import helmet from 'helmet';

${imports}

const app = express();

app.use(helmet());
app.use(cors());
app.use(express.json());

// Health check
app.get('/health', (_req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// Routes
${routes}

// 404
app.use((_req, res) => {
  res.status(404).json({ error: 'Route not found' });
});

export default app;
`;
}

function generateRouteFile(resource: string, endpoints: Blueprint['endpoints']): string {
  const filtered = endpoints.filter((ep) => {
    const parts = ep.path.split('/').filter(Boolean);
    return parts.length >= 2 && parts[1] === resource;
  });

  let code = `import { Router, Request, Response } from 'express';

const router = Router();

`;

  for (const ep of filtered) {
    // Get the sub-path after /api/<resource>
    const parts = ep.path.split('/').filter(Boolean);
    const subPath = '/' + parts.slice(2).join('/') || '/';
    const expressPath = subPath.replace(/:(\w+)/g, ':$1');
    const method = ep.method.toLowerCase();

    code += `// ${ep.description}${ep.auth ? ' [AUTH]' : ''}
router.${method}('${expressPath}', async (req: Request, res: Response) => {
  try {
    // TODO: Implement ${ep.description}
    res.json({ message: '${ep.description}' });
  } catch (err) {
    res.status(500).json({ error: 'Server error' });
  }
});

`;
  }

  code += 'export default router;\n';
  return code;
}

function generateFrontendPackageJson(bp: Blueprint): string {
  const name = toKebabCase(bp.appName) + '-frontend';
  return JSON.stringify(
    {
      name,
      version: '0.1.0',
      private: true,
      type: 'module',
      scripts: {
        dev: 'vite',
        build: 'tsc && vite build',
        preview: 'vite preview',
      },
      dependencies: {
        axios: '^1.6.2',
        react: '^18.2.0',
        'react-dom': '^18.2.0',
        'react-router-dom': '^6.21.0',
      },
      devDependencies: {
        '@types/react': '^18.2.43',
        '@types/react-dom': '^18.2.17',
        '@vitejs/plugin-react': '^4.2.1',
        autoprefixer: '^10.4.16',
        postcss: '^8.4.32',
        tailwindcss: '^3.3.6',
        typescript: '^5.3.2',
        vite: '^5.0.8',
      },
    },
    null,
    2
  );
}

function generateFrontendPage(screen: Blueprint['screens'][number]): string {
  const componentName = toPascalCase(screen.name.replace(/[^a-zA-Z0-9]/g, ''));
  return `import React from 'react';

/**
 * ${screen.name} ${screen.icon}
 * Components: ${screen.components}
 */
export default function ${componentName}Page() {
  return (
    <div className="p-6">
      <h1 className="text-2xl font-bold mb-4">${screen.icon} ${screen.name}</h1>
      <p className="text-gray-600 mb-6">
        Components needed: ${screen.components}
      </p>
      {/* TODO: Implement ${screen.name} */}
      <div className="border-2 border-dashed border-gray-300 rounded-lg p-8 text-center text-gray-400">
        Implement: ${screen.components}
      </div>
    </div>
  );
}
`;
}

function generateFrontendApp(bp: Blueprint): string {
  const imports = bp.screens
    .map((s) => {
      const name = toPascalCase(s.name.replace(/[^a-zA-Z0-9]/g, ''));
      return `import ${name}Page from './pages/${name}Page';`;
    })
    .join('\n');

  const routes = bp.screens
    .map((s) => {
      const name = toPascalCase(s.name.replace(/[^a-zA-Z0-9]/g, ''));
      const path = s.name.toLowerCase() === 'home' || s.name.toLowerCase() === 'landing'
        ? '/'
        : '/' + toKebabCase(s.name);
      return `        <Route path="${path}" element={<${name}Page />} />`;
    })
    .join('\n');

  return `import React from 'react';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';

${imports}

export default function App() {
  return (
    <BrowserRouter>
      <div className="min-h-screen bg-gray-50">
        {/* Navigation */}
        <nav className="bg-white shadow-sm border-b px-6 py-3">
          <div className="max-w-7xl mx-auto flex items-center justify-between">
            <h1 className="text-xl font-bold">${bp.appName}</h1>
            <div className="flex gap-4">
${bp.screens.slice(0, 6).map((s) => {
  const path = s.name.toLowerCase() === 'home' || s.name.toLowerCase() === 'landing'
    ? '/'
    : '/' + toKebabCase(s.name);
  return `              <Link to="${path}" className="text-sm text-gray-600 hover:text-gray-900">${s.icon} ${s.name}</Link>`;
}).join('\n')}
            </div>
          </div>
        </nav>

        {/* Routes */}
        <main className="max-w-7xl mx-auto py-6">
          <Routes>
${routes}
          </Routes>
        </main>
      </div>
    </BrowserRouter>
  );
}
`;
}

function generateApiClient(bp: Blueprint): string {
  let code = `import axios from 'axios';

const api = axios.create({
  baseURL: import.meta.env.VITE_API_URL || 'http://localhost:3001',
  timeout: 10000,
  headers: { 'Content-Type': 'application/json' },
});

`;

  // Group endpoints by resource
  const groups = new Map<string, Blueprint['endpoints']>();
  for (const ep of bp.endpoints) {
    const parts = ep.path.split('/').filter(Boolean);
    const resource = parts.length >= 2 ? parts[1] : 'misc';
    if (!groups.has(resource)) groups.set(resource, []);
    groups.get(resource)!.push(ep);
  }

  for (const [resource, endpoints] of groups) {
    code += `// ─── ${toPascalCase(resource)} ─────────────────────────────\n\n`;
    for (const ep of endpoints) {
      const parts = ep.path.split('/').filter(Boolean);
      const funcName = toCamelCase(ep.method.toLowerCase() + '_' + parts.slice(1).join('_'));
      const method = ep.method.toLowerCase();
      const hasBody = ['post', 'put', 'patch'].includes(method);

      code += `/** ${ep.description} */\n`;
      code += `export async function ${funcName}(${hasBody ? 'data: Record<string, unknown>' : ''}) {\n`;
      if (hasBody) {
        code += `  const response = await api.${method}('${ep.path}', data);\n`;
      } else {
        code += `  const response = await api.${method}('${ep.path}');\n`;
      }
      code += '  return response.data;\n';
      code += '}\n\n';
    }
  }

  code += 'export default api;\n';
  return code;
}

function generateDockerCompose(bp: Blueprint): string {
  const name = toKebabCase(bp.appName);
  return `version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${name}
      POSTGRES_PASSWORD: ${name}_secret
      POSTGRES_DB: ${name}_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://${name}:${name}_secret@db:5432/${name}_dev
      PORT: 3001
      NODE_ENV: development
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3001

volumes:
  pgdata:
`;
}

function generateReadme(bp: Blueprint): string {
  return `# ${bp.appName}

${bp.description}

**Target Users:** ${bp.targetUsers}
**Complexity:** ${bp.complexity}

> Generated by [BuildX](https://github.com) — AI-powered app blueprint generator.

## Tech Stack

| Layer | Technology |
|---|---|
| Frontend | ${bp.architecture.frontend} |
| Backend | ${bp.architecture.backend} |
| Database | ${bp.architecture.database} |
| Auth | ${bp.architecture.auth} |
| Hosting | ${bp.architecture.hosting} |

## Getting Started

### Prerequisites
- Node.js 18+
- PostgreSQL 15+ (or use Docker)

### Quick Start with Docker

\`\`\`bash
docker-compose up -d
\`\`\`

### Manual Setup

1. **Install dependencies:**
\`\`\`bash
cd backend && npm install
cd ../frontend && npm install
\`\`\`

2. **Set up the database:**
\`\`\`bash
cd backend
cp .env.example .env
# Edit .env with your DATABASE_URL
npx prisma db push
\`\`\`

3. **Start development servers:**
\`\`\`bash
# From root
npm run dev
\`\`\`

Backend: http://localhost:3001
Frontend: http://localhost:5173

## API Endpoints

| Method | Path | Description | Auth |
|---|---|---|---|
${bp.endpoints.map((ep) => `| ${ep.method} | \`${ep.path}\` | ${ep.description} | ${ep.auth ? '✅' : '—'} |`).join('\n')}

## Database Schema

${bp.schema.map((t) => `### ${t.table}\n| Column | Type |\n|---|---|\n${t.columns.map((c) => `| ${c.name} | ${c.type} |`).join('\n')}`).join('\n\n')}

## Screens

${bp.screens.map((s) => `- **${s.icon} ${s.name}** — ${s.components}`).join('\n')}

## Effort Estimation

- **Timeline:** ${bp.effort.time}
- **Complexity:** ${bp.effort.complexity}
- **Cost:** ${bp.effort.cost}
- **Team:** ${bp.effort.team}

---

*This project was scaffolded by BuildX AI Architect.*
`;
}

function generateEnvExample(): string {
  return `# Database
DATABASE_URL=postgresql://user:password@localhost:5432/mydb

# Server
PORT=3001
NODE_ENV=development
`;
}

function generateGitignore(): string {
  return `node_modules/
dist/
.env
*.log
.DS_Store
`;
}

// ─── Main export ───────────────────────────────────────────

export function streamScaffoldZip(bp: Blueprint, res: Response): void {
  const appSlug = toKebabCase(bp.appName);

  res.setHeader('Content-Type', 'application/zip');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename="${appSlug}-scaffold.zip"`
  );

  const archive = archiver('zip', { zlib: { level: 6 } });

  archive.on('error', (err) => {
    console.error('[Scaffold] Archive error:', err);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Failed to generate project ZIP' });
    }
  });

  archive.pipe(res);

  // ─── Root files ────────────────────────────────────────
  archive.append(generateRootPackageJson(bp), { name: 'package.json' });
  archive.append(generateDockerCompose(bp), { name: 'docker-compose.yml' });
  archive.append(generateReadme(bp), { name: 'README.md' });
  archive.append(generateGitignore(), { name: '.gitignore' });

  // ─── Backend ───────────────────────────────────────────
  archive.append(generateBackendPackageJson(bp), { name: 'backend/package.json' });
  archive.append(generateBackendTsconfig(), { name: 'backend/tsconfig.json' });
  archive.append(generateEnvExample(), { name: 'backend/.env.example' });
  archive.append(generatePrismaSchema(bp), { name: 'backend/prisma/schema.prisma' });
  archive.append(generateBackendIndex(bp), { name: 'backend/src/index.ts' });
  archive.append(generateBackendApp(bp), { name: 'backend/src/app.ts' });

  // Route files — one per resource
  const resources = new Set<string>();
  for (const ep of bp.endpoints) {
    const parts = ep.path.split('/').filter(Boolean);
    if (parts.length >= 2) resources.add(parts[1]);
  }
  for (const resource of resources) {
    archive.append(generateRouteFile(resource, bp.endpoints), {
      name: `backend/src/routes/${resource}.ts`,
    });
  }

  // ─── Frontend ──────────────────────────────────────────
  archive.append(generateFrontendPackageJson(bp), { name: 'frontend/package.json' });
  archive.append(generateFrontendApp(bp), { name: 'frontend/src/App.tsx' });
  archive.append(
    `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App';\nimport './index.css';\n\nReactDOM.createRoot(document.getElementById('root')!).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>\n);\n`,
    { name: 'frontend/src/main.tsx' }
  );
  archive.append('@tailwind base;\n@tailwind components;\n@tailwind utilities;\n', {
    name: 'frontend/src/index.css',
  });
  archive.append(generateApiClient(bp), { name: 'frontend/src/lib/api.ts' });

  // Page files — one per screen
  for (const screen of bp.screens) {
    const name = toPascalCase(screen.name.replace(/[^a-zA-Z0-9]/g, ''));
    archive.append(generateFrontendPage(screen), {
      name: `frontend/src/pages/${name}Page.tsx`,
    });
  }

  // Index HTML
  archive.append(
    `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8" />\n  <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n  <title>${bp.appName}</title>\n</head>\n<body>\n  <div id="root"></div>\n  <script type="module" src="/src/main.tsx"></script>\n</body>\n</html>\n`,
    { name: 'frontend/index.html' }
  );

  // SQL file
  archive.append(bp.code.sql, { name: 'backend/schema.sql' });

  archive.finalize();
}
