import archiver from 'archiver';
import { Response } from 'express';
import type { Blueprint } from './types';

// ─── Helpers ───────────────────────────────────────────────

function toSnakeCase(str: string): string {
  return str
    .replace(/([a-z])([A-Z])/g, '$1_$2')
    .replace(/[\s\-]+/g, '_')
    .toLowerCase();
}

function toKebabCase(str: string): string {
  return str
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase();
}

function toPascalCase(str: string): string {
  return str
    .replace(/[\s_\-]+(.)/g, (_, c) => c.toUpperCase())
    .replace(/^(.)/, (_, c) => c.toUpperCase());
}

function toCamelCase(str: string): string {
  const pascal = toPascalCase(str);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

/** Map SQL types to Prisma scalar types */
function sqlTypeToPrisma(sqlType: string, isMongo: boolean): string {
  const t = sqlType.toUpperCase();
  if (t.includes('UUID')) return isMongo ? 'String' : 'String @default(uuid())';
  if (t.includes('SERIAL') || t.includes('BIGSERIAL')) return isMongo ? 'Int' : 'Int @default(autoincrement())';
  if (t.includes('INT')) return 'Int';
  if (t.includes('FLOAT') || t.includes('DOUBLE') || t.includes('DECIMAL') || t.includes('NUMERIC'))
    return 'Float';
  if (t.includes('BOOL')) return 'Boolean';
  if (t.includes('TIMESTAMP') || t.includes('DATE')) return 'DateTime';
  if (t.includes('JSON')) return isMongo ? 'Json' : 'Json'; // Json is supported on both
  if (t.includes('TEXT')) return 'String';
  if (t.includes('VARCHAR')) return 'String';
  return 'String';
}

function isPrimaryKey(col: { name: string; type: string; note?: string }): boolean {
  const t = (col.type + ' ' + (col.note || '')).toUpperCase();
  return t.includes('PRIMARY KEY') || t.includes('PK');
}

function hasDefault(type: string): boolean {
  return type.toUpperCase().includes('DEFAULT');
}

// ─── File generators ───────────────────────────────────────

function generateRootPackageJson(bp: Blueprint): string {
  const name = toKebabCase(bp.appName);
  return JSON.stringify(
    {
      name,
      version: '0.1.0',
      private: true,
      description: bp.description,
      scripts: {
        'dev:backend': 'cd backend && npm run dev',
        'dev:frontend': 'cd frontend && npm run dev',
        dev: 'concurrently "npm run dev:backend" "npm run dev:frontend"',
        install: 'cd backend && npm install && cd ../frontend && npm install',
      },
      devDependencies: {
        concurrently: '^8.2.2',
      },
    },
    null,
    2
  );
}

function generateBackendPackageJson(bp: Blueprint): string {
  const name = toKebabCase(bp.appName) + '-backend';
  const isMongo = bp.architecture.database.toLowerCase().includes('mongo');
  
  const dependencies: Record<string, string> = {
    cors: '^2.8.5',
    dotenv: '^16.3.1',
    express: '^4.18.2',
    helmet: '^7.1.0',
    zod: '^3.22.4',
  };
  
  const devDependencies: Record<string, string> = {
    '@types/cors': '^2.8.17',
    '@types/express': '^4.17.21',
    '@types/node': '^20.10.0',
    'ts-node-dev': '^2.0.0',
    typescript: '^5.3.2',
  };

  if (isMongo) {
    dependencies['mongoose'] = '^8.0.0';
  } else {
    dependencies['@prisma/client'] = '^5.7.0';
    devDependencies['prisma'] = '^5.7.0';
  }

  return JSON.stringify(
    {
      name,
      version: '0.1.0',
      private: true,
      scripts: {
        dev: 'ts-node-dev --respawn --transpile-only src/index.ts',
        build: 'tsc',
        start: 'node dist/index.js',
      },
      dependencies,
      devDependencies,
    },
    null,
    2
  );
}

function generateBackendTsconfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2020',
        module: 'commonjs',
        lib: ['ES2020'],
        outDir: './dist',
        rootDir: './src',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
        resolveJsonModule: true,
        sourceMap: true,
      },
      include: ['src/**/*'],
      exclude: ['node_modules', 'dist'],
    },
    null,
    2
  );
}

function generatePrismaSchema(bp: Blueprint): string {
  const isMongo = bp.architecture.database.toLowerCase().includes('mongo');
  const provider = isMongo ? 'mongodb' : 'postgresql';
  let schema = `// Prisma schema generated by BuildX
// https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "${provider}"
  url      = env("DATABASE_URL")
}
`;

  for (const table of bp.schema) {
    const modelName = toPascalCase(table.table);
    schema += `\nmodel ${modelName} {\n`;

    for (const col of table.columns) {
      const fieldName = toCamelCase(col.name);
      let prismaType = sqlTypeToPrisma(col.type, isMongo);

      // Handle primary key
      if (isPrimaryKey(col)) {
        if (isMongo) {
          prismaType = 'String @id @default(auto()) @map("_id") @db.ObjectId';
        } else {
          prismaType = prismaType.includes('@default')
            ? prismaType + ' @id'
            : prismaType + ' @id @default(autoincrement())';
        }
      }

      // Handle unique
      if (col.type.toUpperCase().includes('UNIQUE')) {
        prismaType += ' @unique';
      }

      // Handle NOT NULL — Prisma fields are required by default, add ? for nullable
      const isRequired = col.type.toUpperCase().includes('NOT NULL') || isPrimaryKey(col);
      const typeStr = isRequired ? prismaType : prismaType + '?';

      // Handle default timestamps
      if (col.type.toUpperCase().includes('DEFAULT NOW()') || col.type.toUpperCase().includes('DEFAULT CURRENT_TIMESTAMP')) {
        schema += `  ${fieldName.padEnd(20)} DateTime  @default(now())\n`;
      } else {
        schema += `  ${fieldName.padEnd(20)} ${typeStr}\n`;
      }
    }

    schema += '}\n';
  }

  return schema;
}

function generateBackendIndex(bp: Blueprint): string {
  return `import 'dotenv/config';
import app from './app';

const PORT = parseInt(process.env.PORT || '3001', 10);

app.listen(PORT, () => {
  console.log(\`\\n⚡ ${bp.appName} API running on http://localhost:\${PORT}\`);
  console.log(\`   ENV: \${process.env.NODE_ENV || 'development'}\\n\`);
});
`;
}

function generateBackendApp(bp: Blueprint): string {
  // Collect unique resource names from endpoints
  const resources = new Set<string>();
  for (const ep of bp.endpoints) {
    const parts = ep.path.split('/').filter(Boolean);
    // e.g. /api/auth/login → auth, /api/products → products
    if (parts.length >= 2) {
      resources.add(parts[1]);
    }
  }

  const imports = Array.from(resources)
    .map((r) => `import ${toCamelCase(r)}Router from './routes/${r}';`)
    .join('\n');

  const routes = Array.from(resources)
    .map((r) => `app.use('/api/${r}', ${toCamelCase(r)}Router);`)
    .join('\n');

  return `import express from 'express';
import cors from 'cors';
import helmet from 'helmet';

${imports}

const app = express();

app.use(helmet());
app.use(cors());
app.use(express.json());

// Health check
app.get('/health', (_req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// Routes
${routes}

// 404
app.use((_req, res) => {
  res.status(404).json({ error: 'Route not found' });
});

export default app;
`;
}

function generateRouteFile(resource: string, endpoints: Blueprint['endpoints']): string {
  const filtered = endpoints.filter((ep) => {
    const parts = ep.path.split('/').filter(Boolean);
    return parts.length >= 2 && parts[1] === resource;
  });

  let code = `import { Router, Request, Response } from 'express';

const router = Router();

`;

  for (const ep of filtered) {
    // Get the sub-path after /api/<resource>
    const parts = ep.path.split('/').filter(Boolean);
    const subPath = '/' + parts.slice(2).join('/') || '/';
    const expressPath = subPath.replace(/:(\w+)/g, ':$1');
    const method = ep.method.toLowerCase();

    code += `// ${ep.description}${ep.auth ? ' [AUTH]' : ''}
router.${method}('${expressPath}', async (req: Request, res: Response) => {
  try {
    // TODO: Implement ${ep.description}
    res.json({ message: '${ep.description}' });
  } catch (err) {
    res.status(500).json({ error: 'Server error' });
  }
});

`;
  }

  code += 'export default router;\n';
  return code;
}

function generateFrontendPackageJson(bp: Blueprint): string {
  const name = toKebabCase(bp.appName) + '-frontend';
  return JSON.stringify(
    {
      name,
      version: '0.1.0',
      private: true,
      type: 'module',
      scripts: {
        dev: 'vite',
        build: 'tsc && vite build',
        preview: 'vite preview',
      },
      dependencies: {
        axios: '^1.6.2',
        react: '^18.2.0',
        'react-dom': '^18.2.0',
        'react-router-dom': '^6.21.0',
      },
      devDependencies: {
        '@types/react': '^18.2.43',
        '@types/react-dom': '^18.2.17',
        '@vitejs/plugin-react': '^4.2.1',
        autoprefixer: '^10.4.16',
        postcss: '^8.4.32',
        tailwindcss: '^3.3.6',
        typescript: '^5.3.2',
        vite: '^5.0.8',
      },
    },
    null,
    2
  );
}

function generateFrontendPage(screen: Blueprint['screens'][number]): string {
  const componentName = toPascalCase(screen.name.replace(/[^a-zA-Z0-9]/g, ''));
  return `import React from 'react';

/**
 * ${screen.name} ${screen.icon}
 * Components: ${screen.components}
 */
export default function ${componentName}Page() {
  return (
    <div className="p-6">
      <h1 className="text-2xl font-bold mb-4">${screen.icon} ${screen.name}</h1>
      <p className="text-gray-600 mb-6">
        Components needed: ${screen.components}
      </p>
      {/* TODO: Implement ${screen.name} */}
      <div className="border-2 border-dashed border-gray-300 rounded-lg p-8 text-center text-gray-400">
        Implement: ${screen.components}
      </div>
    </div>
  );
}
`;
}

function generateFrontendApp(bp: Blueprint): string {
  const name = bp.appName || 'BuildX App';
  const desc = bp.description || '';
  const domainLower = (name + ' ' + desc + ' ' + JSON.stringify(bp.screens || []) + ' ' + JSON.stringify(bp.features || {})).toLowerCase();

  const isCrm = domainLower.includes('crm') || domainLower.includes('pipeline') || domainLower.includes('sales') || domainLower.includes('deal') || domainLower.includes('lead') || domainLower.includes('flowcrm');
  const isMedical = domainLower.includes('med') || domainLower.includes('health') || domainLower.includes('patient') || domainLower.includes('doctor') || domainLower.includes('clinic') || domainLower.includes('triage') || domainLower.includes('hospital');
  const isDev = domainLower.includes('code') || domainLower.includes('dev') || domainLower.includes('infra') || domainLower.includes('cloud') || domainLower.includes('server') || domainLower.includes('deploy') || domainLower.includes('api') || domainLower.includes('git');
  const isEcommerce = domainLower.includes('food') || domainLower.includes('fit') || domainLower.includes('order') || domainLower.includes('store') || domainLower.includes('shop') || domainLower.includes('cart') || domainLower.includes('delivery') || domainLower.includes('commerce');

  if (isCrm) {
    return `import React, { useState } from 'react';

export default function App() {
  const [selectedDeal, setSelectedDeal] = useState<any>(null);
  const [filter, setFilter] = useState('all');
  const [searchQuery, setSearchQuery] = useState('');

  const metrics = [
    { label: 'MRR', value: '$184,200', change: '+14.2%', note: 'vs last month' },
    { label: 'Active Deals', value: '42', change: '+8', note: 'in pipeline' },
    { label: 'Win Rate', value: '84.2%', change: '+3.1%', note: 'target 80%' },
    { label: 'Avg Deal Size', value: '$24,500', change: '+$2.1k', note: 'Q3 average' },
  ];

  const deals = [
    { id: 'DEAL-9041', company: 'Acme Corp', val: '$24,000', stage: 'qualified', priority: 'High', rep: 'Sarah K.', avatar: 'AC', days: '3 days in stage', email: 'sarah.k@acme.corp', phone: '+1 (555) 019-2834', notes: 'Evaluating Enterprise Tier for 250 seats.' },
    { id: 'DEAL-9042', company: 'Vercel Inc', val: '$48,500', stage: 'qualified', priority: 'Critical', rep: 'Alex M.', avatar: 'VC', days: '1 day in stage', email: 'alex.m@vercel.com', phone: '+1 (555) 012-9982', notes: 'Needs SSO SAML integration & custom SLA.' },
    { id: 'DEAL-9043', company: 'Supabase', val: '$15,500', stage: 'qualified', priority: 'Medium', rep: 'David R.', avatar: 'SB', days: '5 days in stage', email: 'david.r@supabase.io', phone: '+1 (555) 014-4431', notes: 'Interested in Postgres database migration assistance.' },
    { id: 'DEAL-9044', company: 'Stripe', val: '$65,000', stage: 'meeting', priority: 'Critical', rep: 'Sarah K.', avatar: 'ST', days: '2 days in stage', email: 'billing@stripe.com', phone: '+1 (555) 018-7721', notes: 'Technical demo completed with VP of Eng.' },
    { id: 'DEAL-9045', company: 'Linear', val: '$32,000', stage: 'meeting', priority: 'High', rep: 'Elena R.', avatar: 'LN', days: '4 days in stage', email: 'elena.r@linear.app', phone: '+1 (555) 011-3329', notes: 'Discussing annual prepay discount.' },
    { id: 'DEAL-9046', company: 'OpenAI', val: '$95,000', stage: 'meeting', priority: 'Critical', rep: 'Alex M.', avatar: 'AI', days: '1 day in stage', email: 'procurement@openai.com', phone: '+1 (555) 017-8812', notes: 'Security audit questionnaire submitted.' },
    { id: 'DEAL-9047', company: 'Datadog', val: '$42,000', stage: 'proposal', priority: 'High', rep: 'David R.', avatar: 'DD', days: '6 days in stage', email: 'ops@datadog.com', phone: '+1 (555) 013-5591', notes: 'Proposal v2 delivered. Legal reviewing redlines.' },
    { id: 'DEAL-9048', company: 'Figma', val: '$54,000', stage: 'proposal', priority: 'High', rep: 'Sarah K.', avatar: 'FG', days: '2 days in stage', email: 'design@figma.com', phone: '+1 (555) 016-1120', notes: 'Contract sent via DocuSign.' },
    { id: 'DEAL-9049', company: 'GitHub', val: '$120,000', stage: 'won', priority: 'Critical', rep: 'Alex M.', avatar: 'GH', days: 'Closed Today', email: 'partners@github.com', phone: '+1 (555) 019-9944', notes: 'Signed 3-year enterprise contract!' },
    { id: 'DEAL-9050', company: 'Notion', val: '$28,000', stage: 'won', priority: 'High', rep: 'Elena R.', avatar: 'NT', days: 'Closed Yesterday', email: 'sales@notion.so', phone: '+1 (555) 015-6677', notes: 'Kickoff call scheduled for Monday.' },
  ];

  const columns = [
    { id: 'qualified', title: 'Qualified', color: 'text-blue-400 border-blue-500/30' },
    { id: 'meeting', title: 'Meeting Scheduled', color: 'text-indigo-400 border-indigo-500/30' },
    { id: 'proposal', title: 'Proposal Sent', color: 'text-purple-400 border-purple-500/30' },
    { id: 'won', title: 'Closed Won', color: 'text-emerald-400 border-emerald-500/30' },
  ];

  const filteredDeals = deals.filter(d => {
    if (searchQuery && !d.company.toLowerCase().includes(searchQuery.toLowerCase()) && !d.id.toLowerCase().includes(searchQuery.toLowerCase())) return false;
    if (filter === 'enterprise' && parseInt(d.val.replace(/[^0-9]/g, '')) < 40000) return false;
    if (filter === 'critical' && d.priority !== 'Critical') return false;
    return true;
  });

  return (
    <div className="min-h-screen bg-[#09090b] text-zinc-100 font-sans p-6">
      <header className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-6 mb-6 border-b border-white/10">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl font-bold text-white tracking-tight">${name}</h1>
            <span className="px-2 py-0.5 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 font-mono text-[10px]">
              LIVE PIPELINE
            </span>
          </div>
          <p className="text-xs text-zinc-400 font-mono mt-1">REAL-TIME REVENUE & DEAL STAGE TELEMETRY</p>
        </div>

        <div className="flex items-center gap-3">
          <input
            type="text"
            placeholder="Search deals, companies, IDs..."
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
            className="px-3 py-1.5 rounded-xl bg-zinc-900 border border-white/10 text-xs text-zinc-200 placeholder-zinc-500 focus:outline-none focus:border-indigo-500 font-mono w-64"
          />
          <button className="px-4 py-2 rounded-xl bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 text-white font-semibold text-xs transition-all shadow-lg shadow-indigo-500/20">
            + Add Deal
          </button>
        </div>
      </header>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        {metrics.map((m, idx) => (
          <div key={idx} className="bg-zinc-900/80 border border-white/10 backdrop-blur-xl rounded-2xl p-4 shadow-2xl">
            <span className="font-mono text-[10px] text-zinc-500 uppercase tracking-widest block">{m.label}</span>
            <div className="flex items-baseline justify-between mt-1">
              <span className="text-xl font-bold text-white font-mono">{m.value}</span>
              <span className="text-xs font-mono px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                {m.change}
              </span>
            </div>
            <span className="text-[10px] text-zinc-500 mt-1 block font-mono">{m.note}</span>
          </div>
        ))}
      </div>

      <div className="flex items-center justify-between gap-4 mb-4 bg-zinc-900/40 p-2 rounded-xl border border-white/5">
        <div className="flex items-center gap-2">
          <span className="text-xs text-zinc-400 font-mono pl-2">Filter:</span>
          {['all', 'enterprise', 'critical'].map(f => (
            <button
              key={f}
              onClick={() => setFilter(f)}
              className={\`px-3 py-1 rounded-lg text-xs font-mono capitalize transition-all \${
                filter === f ? 'bg-indigo-600/30 text-indigo-300 border border-indigo-500/40' : 'text-zinc-400 hover:text-white'
              }\`}
            >
              {f === 'all' ? 'All Reps' : f === 'enterprise' ? 'Enterprise Only ($40k+)' : 'Critical Only'}
            </button>
          ))}
        </div>
        <span className="text-xs text-zinc-500 font-mono pr-2">{filteredDeals.length} deals active</span>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        {columns.map(col => {
          const colDeals = filteredDeals.filter(d => d.stage === col.id);
          const colTotal = colDeals.reduce((sum, d) => sum + parseInt(d.val.replace(/[^0-9]/g, '') || '0'), 0);

          return (
            <div key={col.id} className="bg-zinc-900/50 border border-white/10 rounded-2xl p-3 flex flex-col gap-3 min-h-[480px]">
              <div className="flex items-center justify-between pb-2 border-b border-white/5">
                <span className={\`text-xs font-bold uppercase tracking-wider font-mono \${col.color.split(' ')[0]}\`}>
                  {col.title} ({colDeals.length})
                </span>
                <span className="font-mono text-xs text-zinc-400">\${colTotal.toLocaleString()}</span>
              </div>

              <div className="space-y-3 flex-1 overflow-y-auto">
                {colDeals.map(deal => (
                  <div
                    key={deal.id}
                    onClick={() => setSelectedDeal(deal)}
                    className="bg-zinc-900/90 hover:bg-zinc-800/90 border border-white/10 hover:border-indigo-500/40 rounded-xl p-3.5 shadow-lg transition-all cursor-pointer space-y-2.5 group"
                  >
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <div className="w-6 h-6 rounded-lg bg-indigo-500/20 border border-indigo-500/30 text-indigo-300 flex items-center justify-center font-bold text-[10px] font-mono">
                          {deal.avatar}
                        </div>
                        <span className="font-semibold text-xs text-white group-hover:text-indigo-300 transition-colors">
                          {deal.company}
                        </span>
                      </div>
                      <span className="font-mono text-xs font-bold text-emerald-400">{deal.val}</span>
                    </div>

                    <div className="flex items-center justify-between text-[10px] font-mono text-zinc-400">
                      <span className="text-zinc-500">{deal.id}</span>
                      <span className={\`px-1.5 py-0.5 rounded border \${
                        deal.priority === 'Critical' ? 'bg-red-500/10 text-red-400 border-red-500/20' : 'bg-amber-500/10 text-amber-400 border-amber-500/20'
                      }\`}>
                        {deal.priority}
                      </span>
                    </div>

                    <div className="flex items-center justify-between pt-2 border-t border-white/5 text-[10px] font-mono text-zinc-500">
                      <span>👤 {deal.rep}</span>
                      <span>⏱ {deal.days}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          );
        })}
      </div>

      {selectedDeal && (
        <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex justify-end" onClick={() => setSelectedDeal(null)}>
          <div className="w-full max-w-md bg-[#121216] border-l border-white/10 p-6 flex flex-col gap-5 h-full overflow-y-auto" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between pb-4 border-b border-white/10">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-indigo-500/20 border border-indigo-500/30 text-indigo-300 flex items-center justify-center font-bold text-sm font-mono">
                  {selectedDeal.avatar}
                </div>
                <div>
                  <h3 className="text-base font-bold text-white">{selectedDeal.company}</h3>
                  <span className="text-xs font-mono text-zinc-400">{selectedDeal.id}</span>
                </div>
              </div>
              <button onClick={() => setSelectedDeal(null)} className="p-1 rounded-lg hover:bg-white/10 text-zinc-400 text-xs">✕</button>
            </div>

            <div className="space-y-4 font-mono text-xs">
              <div className="bg-zinc-900/80 p-4 rounded-xl border border-white/10 space-y-2">
                <div className="flex justify-between"><span className="text-zinc-500">Deal Value:</span><span className="text-emerald-400 font-bold">{selectedDeal.val}</span></div>
                <div className="flex justify-between"><span className="text-zinc-500">Priority:</span><span className="text-amber-400">{selectedDeal.priority}</span></div>
                <div className="flex justify-between"><span className="text-zinc-500">Assigned Rep:</span><span className="text-white">{selectedDeal.rep}</span></div>
                <div className="flex justify-between"><span className="text-zinc-500">Stage Duration:</span><span className="text-zinc-300">{selectedDeal.days}</span></div>
              </div>

              <div className="bg-zinc-900/80 p-4 rounded-xl border border-white/10 space-y-2">
                <span className="text-zinc-400 font-bold block mb-2">Contact Details</span>
                <div className="flex justify-between"><span className="text-zinc-500">Email:</span><span className="text-indigo-400">{selectedDeal.email}</span></div>
                <div className="flex justify-between"><span className="text-zinc-500">Phone:</span><span className="text-zinc-300">{selectedDeal.phone}</span></div>
              </div>

              <div className="bg-zinc-900/80 p-4 rounded-xl border border-white/10 space-y-2">
                <span className="text-zinc-400 font-bold block mb-2">Activity History</span>
                <p className="text-zinc-300 font-sans text-xs leading-relaxed">{selectedDeal.notes}</p>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
`;
  }

  if (isMedical) {
    return `import React, { useState } from 'react';

export default function App() {
  const [selectedPatient, setSelectedPatient] = useState<any>(null);
  const [filter, setFilter] = useState('all');
  const [search, setSearch] = useState('');

  const metrics = [
    { label: 'Active Patients', val: '28', status: '2 In ICU' },
    { label: 'On-Call Physicians', val: '4', status: 'Active Shift' },
    { label: 'System SLA', val: '99.8%', status: 'HIPAA Compliant' },
    { label: 'Triage Queue', val: '12', status: 'Avg 4.2m Wait' },
  ];

  const patients = [
    { mrn: '#MRN-8942', name: 'Eleanor Vance', age: 48, status: 'Triage', bp: '138/88 mmHg', hr: '84 bpm', spo2: '97%', doctor: 'Dr. Vance', room: 'Bay 4', notes: 'Acute chest discomfort, ECG normal.' },
    { mrn: '#MRN-9104', name: 'Marcus Brody', age: 62, status: 'In Consultation', bp: '120/80 mmHg', hr: '72 bpm', spo2: '99%', doctor: 'Dr. Chen', room: 'Exam 2', notes: 'Routine post-op checkup.' },
    { mrn: '#MRN-7731', name: 'Sophia Martinez', age: 34, status: 'Discharged', bp: '118/76 mmHg', hr: '68 bpm', spo2: '98%', doctor: 'Dr. Al-Mansoor', room: 'Outpatient', notes: 'Medication prescribed, follow up in 2 weeks.' },
    { mrn: '#MRN-6420', name: 'Jonathan Reed', age: 55, status: 'Observation', bp: '142/92 mmHg', hr: '90 bpm', spo2: '95%', doctor: 'Dr. Ramirez', room: 'Bed 12', notes: 'Elevated blood pressure, monitoring response.' },
    { mrn: '#MRN-8193', name: 'Clara Oswald', age: 29, status: 'Triage', bp: '110/70 mmHg', hr: '75 bpm', spo2: '99%', doctor: 'Dr. Vance', room: 'Bay 1', notes: 'Mild fever and dehydration.' },
    { mrn: '#MRN-5512', name: 'Arthur Pendelton', age: 71, status: 'In Consultation', bp: '135/85 mmHg', hr: '80 bpm', spo2: '96%', doctor: 'Dr. Chen', room: 'Exam 4', notes: 'Joint mobility assessment.' },
  ];

  const filtered = patients.filter(p => {
    if (search && !p.name.toLowerCase().includes(search.toLowerCase()) && !p.mrn.toLowerCase().includes(search.toLowerCase())) return false;
    if (filter !== 'all' && p.status.toLowerCase() !== filter) return false;
    return true;
  });

  return (
    <div className="min-h-screen bg-[#09090b] text-zinc-100 font-sans p-6">
      <header className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-6 mb-6 border-b border-white/10">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl font-bold text-white tracking-tight">${name}</h1>
            <span className="px-2 py-0.5 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 font-mono text-[10px]">
              HIPAA COMPLIANT
            </span>
          </div>
          <p className="text-xs text-zinc-400 font-mono mt-1">PATIENT TRIAGE & CLINICAL TELEMETRY QUEUE</p>
        </div>

        <div className="flex items-center gap-3">
          <input
            type="text"
            placeholder="Search patients, records, MRNs..."
            value={search}
            onChange={e => setSearch(e.target.value)}
            className="px-3 py-1.5 rounded-xl bg-zinc-900 border border-white/10 text-xs text-zinc-200 placeholder-zinc-500 focus:outline-none focus:border-indigo-500 font-mono w-64"
          />
        </div>
      </header>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        {metrics.map((m, i) => (
          <div key={i} className="bg-zinc-900/80 border border-white/10 backdrop-blur-xl rounded-2xl p-4 shadow-2xl">
            <span className="font-mono text-[10px] text-zinc-500 uppercase tracking-widest block">{m.label}</span>
            <div className="flex items-baseline justify-between mt-1">
              <span className="text-xl font-bold text-white font-mono">{m.val}</span>
              <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
                {m.status}
              </span>
            </div>
          </div>
        ))}
      </div>

      <div className="bg-zinc-900/80 border border-white/10 backdrop-blur-xl rounded-2xl overflow-hidden shadow-2xl">
        <div className="p-4 border-b border-white/10 flex items-center justify-between">
          <span className="font-mono text-xs text-zinc-300 font-bold">CLINICAL PATIENT QUEUE</span>
          <div className="flex gap-2">
            {['all', 'triage', 'in consultation', 'discharged'].map(s => (
              <button
                key={s}
                onClick={() => setFilter(s)}
                className={\`px-2.5 py-1 rounded-lg text-[11px] font-mono capitalize \${filter === s ? 'bg-indigo-600/30 text-indigo-300 border border-indigo-500/40' : 'text-zinc-400 hover:text-white'}\`}
              >
                {s}
              </button>
            ))}
          </div>
        </div>

        <table className="w-full text-left font-mono text-xs">
          <thead className="bg-zinc-950 text-zinc-500 border-b border-white/10 text-[10px] uppercase tracking-wider">
            <tr>
              <th className="p-4">MRN</th>
              <th className="p-4">Patient Name</th>
              <th className="p-4">Status</th>
              <th className="p-4">Vital Signs</th>
              <th className="p-4">Attending Doctor</th>
              <th className="p-4 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-white/5 text-zinc-300">
            {filtered.map(p => (
              <tr key={p.mrn} onClick={() => setSelectedPatient(p)} className="hover:bg-white/5 cursor-pointer transition-colors">
                <td className="p-4 font-bold text-indigo-400">{p.mrn}</td>
                <td className="p-4 font-sans font-semibold text-white">{p.name} <span className="text-xs text-zinc-500">({p.age}y)</span></td>
                <td className="p-4">
                  <span className={\`px-2 py-0.5 rounded-full border text-[10px] \${
                    p.status === 'Triage' ? 'bg-amber-500/10 text-amber-400 border-amber-500/20' :
                    p.status === 'Discharged' ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20' :
                    'bg-indigo-500/10 text-indigo-400 border border-indigo-500/20'
                  }\`}>
                    {p.status}
                  </span>
                </td>
                <td className="p-4 text-zinc-300">{p.bp} · {p.hr} · {p.spo2}</td>
                <td className="p-4 text-zinc-400">{p.doctor}</td>
                <td className="p-4 text-right">
                  <button className="px-2.5 py-1 bg-white/5 hover:bg-white/10 rounded border border-white/10 text-xs">View Chart</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {selectedPatient && (
        <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex justify-end" onClick={() => setSelectedPatient(null)}>
          <div className="w-full max-w-md bg-[#121216] border-l border-white/10 p-6 flex flex-col gap-4 h-full overflow-y-auto" onClick={e => e.stopPropagation()}>
            <div className="flex justify-between items-center pb-4 border-b border-white/10">
              <div>
                <h3 className="text-base font-bold text-white">{selectedPatient.name}</h3>
                <span className="text-xs font-mono text-indigo-400">{selectedPatient.mrn}</span>
              </div>
              <button onClick={() => setSelectedPatient(null)} className="text-zinc-400 hover:text-white">✕</button>
            </div>
            <div className="space-y-3 font-mono text-xs">
              <div className="bg-zinc-900 p-4 rounded-xl border border-white/10 space-y-2">
                <div className="flex justify-between"><span className="text-zinc-500">Blood Pressure:</span><span className="text-white">{selectedPatient.bp}</span></div>
                <div className="flex justify-between"><span className="text-zinc-500">Heart Rate:</span><span className="text-white">{selectedPatient.hr}</span></div>
                <div className="flex justify-between"><span className="text-zinc-500">Oxygen Saturation:</span><span className="text-emerald-400">{selectedPatient.spo2}</span></div>
                <div className="flex justify-between"><span className="text-zinc-500">Assigned Location:</span><span className="text-zinc-300">{selectedPatient.room}</span></div>
              </div>
              <div className="bg-zinc-900 p-4 rounded-xl border border-white/10">
                <span className="text-zinc-400 font-bold block mb-2">Clinical Notes & Diagnosis</span>
                <p className="text-zinc-300 font-sans text-xs leading-relaxed">{selectedPatient.notes}</p>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
`;
  }

  if (isDev) {
    return `import React, { useState } from 'react';

export default function App() {
  const metrics = [
    { label: 'CPU Usage', val: '24.8%', status: 'Normal' },
    { label: 'Memory Usage', val: '4.2 / 16 GB', status: 'Stable' },
    { label: 'API Latency', val: '24ms avg', status: 'p95 18ms' },
    { label: 'System Uptime', val: '99.99%', status: 'SLA Met' },
  ];

  const endpoints = [
    { path: '/api/v1/auth/verify', latency: '18ms', status: '200 OK', load: '1,420 req/s' },
    { path: '/api/v1/deployments', latency: '34ms', status: '200 OK', load: '840 req/s' },
    { path: '/api/v1/webhooks', latency: '12ms', status: '200 OK', load: '3,100 req/s' },
    { path: '/api/v1/analytics', latency: '42ms', status: '200 OK', load: '520 req/s' },
  ];

  const logs = [
    '10:42:01.104 [sys] Container build succeeded in 3.4s',
    '10:42:02.310 [net] Route /api/v1/deployments bound to port 3001',
    '10:42:03.001 [db] Postgres connection pool initialized (10 connections)',
    '10:42:04.882 [auth] OAuth provider GitHub verified successfully',
  ];

  return (
    <div className="min-h-screen bg-[#09090b] text-zinc-100 font-mono text-xs p-6">
      <header className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-6 mb-6 border-b border-white/10">
        <div>
          <div className="flex items-center gap-3">
            <span className="flex items-center gap-1.5 text-xs text-emerald-400 font-bold">
              <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" /> ● All Systems Operational
            </span>
            <span className="text-zinc-600">|</span>
            <span className="text-zinc-400">Environment: Production (us-east-1)</span>
          </div>
          <h1 className="text-xl font-bold text-white font-sans mt-1">${name} Developer Console</h1>
        </div>

        <div className="flex items-center gap-3">
          <span className="px-3 py-1.5 rounded-xl bg-zinc-900 border border-white/10 text-zinc-400 text-xs">
            Commit: <span className="text-indigo-400">v2.4.1-beta</span>
          </span>
          <button className="px-4 py-2 rounded-xl bg-gradient-to-r from-indigo-600 to-purple-600 text-white font-sans font-semibold text-xs">
            + New Deployment
          </button>
        </div>
      </header>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        {metrics.map((m, i) => (
          <div key={i} className="bg-zinc-900/80 border border-white/10 backdrop-blur-xl rounded-2xl p-4 shadow-2xl">
            <span className="text-[10px] text-zinc-500 uppercase tracking-widest block">{m.label}</span>
            <div className="flex items-baseline justify-between mt-1">
              <span className="text-xl font-bold text-white">{m.val}</span>
              <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">{m.status}</span>
            </div>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="bg-zinc-900/80 border border-white/10 backdrop-blur-xl rounded-2xl p-4 shadow-2xl space-y-3">
          <span className="text-zinc-300 font-bold block border-b border-white/10 pb-2">API ENDPOINT LATENCY & HEALTH</span>
          <div className="space-y-2">
            {endpoints.map((ep, i) => (
              <div key={i} className="flex items-center justify-between p-2.5 rounded-xl bg-black/40 border border-white/5">
                <span className="text-indigo-300 font-bold">{ep.path}</span>
                <div className="flex items-center gap-3">
                  <span className="text-zinc-400">{ep.load}</span>
                  <span className="text-emerald-400 font-bold">{ep.latency}</span>
                  <span className="px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400 text-[10px]">{ep.status}</span>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="bg-zinc-900/80 border border-white/10 backdrop-blur-xl rounded-2xl p-4 shadow-2xl space-y-3">
          <span className="text-zinc-300 font-bold block border-b border-white/10 pb-2">DEPLOYMENT LOG STREAM</span>
          <div className="bg-black/60 p-3 rounded-xl border border-white/10 space-y-1.5 text-[11px] text-zinc-400 font-mono">
            {logs.map((l, i) => (
              <div key={i} className="leading-relaxed hover:text-zinc-200">{l}</div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
`;
  }

  if (isEcommerce) {
    return `import React, { useState } from 'react';

export default function App() {
  const [filter, setFilter] = useState('all');

  const orders = [
    { id: '#ORD-9421', customer: 'Elena Rostova', items: '2x Organic Acai Bowl, 1x Cold Brew', total: '$38.50', status: 'In Transit', driver: 'Marcus V. · ETA 12 mins' },
    { id: '#ORD-9422', customer: 'Michael Chang', items: '1x Salmon Poke Bowl, 1x Green Juice', total: '$27.80', status: 'Preparing', driver: 'Assigning driver...' },
    { id: '#ORD-9423', customer: 'Sarah Jenkins', items: '3x Avocado Toast, 2x Espresso', total: '$44.00', status: 'Delivered', driver: 'Completed' },
    { id: '#ORD-9424', customer: 'David Kim', items: '1x Protein Smoothie Bowl', total: '$14.50', status: 'Pending', driver: 'Awaiting Kitchen' },
  ];

  return (
    <div className="min-h-screen bg-[#09090b] text-zinc-100 font-sans p-6">
      <header className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-6 mb-6 border-b border-white/10">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl font-bold text-white tracking-tight">${name} Operations Console</h1>
            <span className="px-2 py-0.5 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 font-mono text-[10px]">
              LIVE DISPATCH
            </span>
          </div>
          <p className="text-xs text-zinc-400 font-mono mt-1">REAL-TIME FULFILLMENT & DISPATCH MONITOR</p>
        </div>

        <div className="flex items-center gap-3">
          <span className="font-mono text-xs text-zinc-400 bg-zinc-900 px-3 py-1.5 rounded-xl border border-white/10">
            Today's Orders: <span className="text-emerald-400 font-bold">1,240</span> ($34.2k)
          </span>
        </div>
      </header>

      <div className="bg-zinc-900/80 border border-white/10 backdrop-blur-xl rounded-2xl overflow-hidden shadow-2xl">
        <div className="p-4 border-b border-white/10 flex justify-between items-center">
          <span className="font-mono text-xs font-bold text-zinc-300">LIVE ORDER DISPATCH GRID</span>
          <div className="flex gap-2 font-mono text-xs">
            {['all', 'pending', 'preparing', 'in transit', 'delivered'].map(s => (
              <button key={s} onClick={() => setFilter(s)} className={\`px-2.5 py-1 rounded-lg capitalize \${filter === s ? 'bg-indigo-600/30 text-indigo-300 border border-indigo-500/40' : 'text-zinc-400'}\`}>{s}</button>
            ))}
          </div>
        </div>

        <table className="w-full text-left font-mono text-xs">
          <thead className="bg-zinc-950 text-zinc-500 border-b border-white/10 text-[10px] uppercase">
            <tr>
              <th className="p-4">Order ID</th>
              <th className="p-4">Customer</th>
              <th className="p-4">Itemized Receipt</th>
              <th className="p-4">Total</th>
              <th className="p-4">Status</th>
              <th className="p-4">Driver Assignment</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-white/5 text-zinc-300">
            {orders.filter(o => filter === 'all' || o.status.toLowerCase() === filter).map(o => (
              <tr key={o.id} className="hover:bg-white/5 transition-colors">
                <td className="p-4 font-bold text-indigo-400">{o.id}</td>
                <td className="p-4 font-sans text-white">{o.customer}</td>
                <td className="p-4 text-zinc-400">{o.items}</td>
                <td className="p-4 font-bold text-emerald-400">{o.total}</td>
                <td className="p-4">
                  <span className={\`px-2 py-0.5 rounded-full border text-[10px] \${
                    o.status === 'In Transit' ? 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20' :
                    o.status === 'Delivered' ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20' :
                    'bg-amber-500/10 text-amber-400 border-amber-500/20'
                  }\`}>{o.status}</span>
                </td>
                <td className="p-4 text-zinc-400">{o.driver}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
`;
  }

  // Default High-Density SaaS Interface
  return `import React, { useState } from 'react';

export default function App() {
  const [activeTab, setActiveTab] = useState('overview');

  const metrics = [
    { label: 'Monthly Recurring Revenue', value: '$84,200', change: '+18.4%' },
    { label: 'Active Workspace Users', value: '1,420', change: '+12.1%' },
    { label: 'System Availability', value: '99.9%', change: 'SLA OK' },
    { label: 'Open Support Tickets', value: '18', change: '-4' },
  ];

  const items = [
    { id: '#USR-9021', name: 'Acme Corp Admin', status: 'Active', plan: 'Enterprise', usage: '84%', lastSeen: '2m ago' },
    { id: '#USR-9022', name: 'Vercel Workspace', status: 'Active', plan: 'Pro Tier', usage: '62%', lastSeen: '5m ago' },
    { id: '#USR-9023', name: 'Supabase Project', status: 'Pending', plan: 'Starter', usage: '15%', lastSeen: '1h ago' },
    { id: '#USR-9024', name: 'Linear Integration', status: 'Active', plan: 'Enterprise', usage: '91%', lastSeen: 'Just now' },
  ];

  return (
    <div className="min-h-screen bg-[#09090b] text-zinc-100 font-sans p-6">
      <header className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-6 mb-6 border-b border-white/10">
        <div>
          <h1 className="text-xl font-bold text-white tracking-tight">${name}</h1>
          <p className="text-xs text-zinc-400 font-mono mt-1">${desc.slice(0, 80)}...</p>
        </div>
        <div className="flex items-center gap-3">
          <button className="px-4 py-2 rounded-xl bg-gradient-to-r from-indigo-600 to-purple-600 text-white font-semibold text-xs">
            + Create Item
          </button>
        </div>
      </header>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        {metrics.map((m, i) => (
          <div key={i} className="bg-zinc-900/80 border border-white/10 backdrop-blur-xl rounded-2xl p-4 shadow-2xl">
            <span className="font-mono text-[10px] text-zinc-500 uppercase tracking-widest block">{m.label}</span>
            <div className="flex items-baseline justify-between mt-1">
              <span className="text-xl font-bold text-white font-mono">{m.value}</span>
              <span className="text-xs font-mono px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">{m.change}</span>
            </div>
          </div>
        ))}
      </div>

      <div className="bg-zinc-900/80 border border-white/10 backdrop-blur-xl rounded-2xl overflow-hidden shadow-2xl">
        <div className="p-4 border-b border-white/10 flex justify-between items-center">
          <span className="font-mono text-xs font-bold text-zinc-300">WORKSPACE ACTIVITY MONITOR</span>
        </div>
        <table className="w-full text-left font-mono text-xs">
          <thead className="bg-zinc-950 text-zinc-500 border-b border-white/10 text-[10px] uppercase">
            <tr>
              <th className="p-4">ID</th>
              <th className="p-4">Workspace Name</th>
              <th className="p-4">Status</th>
              <th className="p-4">Plan Tier</th>
              <th className="p-4">Quota Usage</th>
              <th className="p-4">Last Activity</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-white/5 text-zinc-300">
            {items.map(item => (
              <tr key={item.id} className="hover:bg-white/5 transition-colors">
                <td className="p-4 font-bold text-indigo-400">{item.id}</td>
                <td className="p-4 font-sans text-white">{item.name}</td>
                <td className="p-4">
                  <span className="px-2 py-0.5 rounded-full border text-[10px] bg-emerald-500/10 text-emerald-400 border-emerald-500/20">{item.status}</span>
                </td>
                <td className="p-4 text-zinc-300">{item.plan}</td>
                <td className="p-4 text-zinc-400">{item.usage}</td>
                <td className="p-4 text-zinc-500">{item.lastSeen}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
`;
}


function generateApiClient(bp: Blueprint): string {
  let code = `import axios from 'axios';

const api = axios.create({
  baseURL: import.meta.env.VITE_API_URL || 'http://localhost:3001',
  timeout: 10000,
  headers: { 'Content-Type': 'application/json' },
});

`;

  // Group endpoints by resource
  const groups = new Map<string, Blueprint['endpoints']>();
  for (const ep of bp.endpoints) {
    const parts = ep.path.split('/').filter(Boolean);
    const resource = parts.length >= 2 ? parts[1] : 'misc';
    if (!groups.has(resource)) groups.set(resource, []);
    groups.get(resource)!.push(ep);
  }

  for (const [resource, endpoints] of groups) {
    code += `// ─── ${toPascalCase(resource)} ─────────────────────────────\n\n`;
    for (const ep of endpoints) {
      const parts = ep.path.split('/').filter(Boolean);
      const funcName = toCamelCase(ep.method.toLowerCase() + '_' + parts.slice(1).join('_'));
      const method = ep.method.toLowerCase();
      const hasBody = ['post', 'put', 'patch'].includes(method);

      code += `/** ${ep.description} */\n`;
      code += `export async function ${funcName}(${hasBody ? 'data: Record<string, unknown>' : ''}) {\n`;
      if (hasBody) {
        code += `  const response = await api.${method}('${ep.path}', data);\n`;
      } else {
        code += `  const response = await api.${method}('${ep.path}');\n`;
      }
      code += '  return response.data;\n';
      code += '}\n\n';
    }
  }

  code += 'export default api;\n';
  return code;
}

function generateDockerCompose(bp: Blueprint): string {
  const name = toKebabCase(bp.appName);
  const isMongo = bp.architecture.database.toLowerCase().includes('mongo');
  
  if (isMongo) {
    return `version: '3.8'

services:
  db:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
      MONGO_INITDB_DATABASE: ${name}_dev
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: mongodb://admin:admin_password@db:27017/${name}_dev?authSource=admin
      PORT: 3001
      NODE_ENV: development
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3001

volumes:
  mongodata:
`;
  }

  return `version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${name}
      POSTGRES_PASSWORD: ${name}_secret
      POSTGRES_DB: ${name}_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://${name}:${name}_secret@db:5432/${name}_dev
      PORT: 3001
      NODE_ENV: development
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3001

volumes:
  pgdata:
`;
}

function generateReadme(bp: Blueprint): string {
  const isMongo = bp.architecture.database.toLowerCase().includes('mongo');
  const dbPrereq = isMongo ? '- MongoDB (or use Docker)' : '- PostgreSQL 15+ (or use Docker)';
  const dbSetupInstructions = isMongo
    ? `cd backend
cp .env.example .env
# Edit .env with your DATABASE_URL`
    : `cd backend
cp .env.example .env
# Edit .env with your DATABASE_URL
npx prisma db push`;

  const schemaHeader = isMongo ? 'Field' : 'Column';
  const dbSchemaSection = bp.schema.map((t) => `### ${t.table}
| ${schemaHeader} | Type |
|---|---|
${t.columns.map((c) => `| ${c.name} | ${c.type} |`).join('\n')}`).join('\n\n');

  return `# ${bp.appName}

${bp.description}

**Target Users:** ${bp.targetUsers}
**Complexity:** ${bp.complexity}

> Generated by [BuildX](https://github.com) — AI-powered app blueprint generator.

## Tech Stack

| Layer | Technology |
|---|---|
| Frontend | ${bp.architecture.frontend} |
| Backend | ${bp.architecture.backend} |
| Database | ${bp.architecture.database} |
| Auth | ${bp.architecture.auth} |
| Hosting | ${bp.architecture.hosting} |

## Getting Started

### Prerequisites
- Node.js 18+
${dbPrereq}

### Quick Start with Docker

\`\`\`bash
docker-compose up -d
\`\`\`

### Manual Setup

1. **Install dependencies:**
\`\`\`bash
cd backend && npm install
cd ../frontend && npm install
\`\`\`

2. **Set up the database:**
\`\`\`bash
${dbSetupInstructions}
\`\`\`

3. **Start development servers:**
\`\`\`bash
# From root
npm run dev
\`\`\`

Backend: http://localhost:3001
Frontend: http://localhost:5173

## API Endpoints

| Method | Path | Description | Auth |
|---|---|---|---|
${bp.endpoints.map((ep) => `| ${ep.method} | \`${ep.path}\` | ${ep.description} | ${ep.auth ? '✅' : '—'} |`).join('\n')}

## Database Schema

${dbSchemaSection}

## Screens

${bp.screens.map((s) => `- **${s.icon} ${s.name}** — ${s.components}`).join('\n')}

## Effort Estimation

- **Timeline:** ${bp.effort.time}
- **Complexity:** ${bp.effort.complexity}
- **Cost:** ${bp.effort.cost}
- **Team:** ${bp.effort.team}

---

*This project was scaffolded by BuildX AI Architect.*
`;
}

function generateEnvExample(bp: Blueprint): string {
  const isMongo = bp.architecture.database.toLowerCase().includes('mongo');
  const defaultUrl = isMongo
    ? 'mongodb://admin:admin_password@localhost:27017/mydb?authSource=admin'
    : 'postgresql://user:password@localhost:5432/mydb';
  
  return `# Database
DATABASE_URL=${defaultUrl}

# Server
PORT=3001
NODE_ENV=development
`;
}

function generateGitignore(): string {
  return `node_modules/
dist/
.env
*.log
.DS_Store
`;
}

// ─── Main export ───────────────────────────────────────────

/** Map SQL column types to Mongoose schema types */
function sqlTypeToMongoose(sqlType: string): string {
  const t = sqlType.toUpperCase();
  if (t.includes('INT') || t.includes('SERIAL') || t.includes('FLOAT') ||
      t.includes('DOUBLE') || t.includes('DECIMAL') || t.includes('NUMERIC')) return 'Number';
  if (t.includes('BOOL')) return 'Boolean';
  if (t.includes('TIMESTAMP') || t.includes('DATE')) return 'Date';
  if (t.includes('JSON')) return 'Object';
  return 'String';
}

/**
 * Generate Mongoose model definitions from the blueprint schema.
 * Used for MongoDB projects so `schema.js` is never empty even when the
 * AI refinement left `code.sql` blank or still containing raw SQL.
 */
function generateMongooseSchema(bp: Blueprint): string {
  let out = `// Mongoose models generated by BuildX\nconst mongoose = require('mongoose');\nconst { Schema } = mongoose;\n`;

  for (const table of bp.schema) {
    const modelName = toPascalCase(table.table);
    out += `\nconst ${toCamelCase(table.table)}Schema = new Schema({\n`;
    const fields = table.columns
      .filter((col) => col.name.toLowerCase() !== 'id' && col.name.toLowerCase() !== '_id')
      .map((col) => {
        const fieldName = toCamelCase(col.name);
        const mType = sqlTypeToMongoose(col.type);
        const required = col.type.toUpperCase().includes('NOT NULL');
        const unique = col.type.toUpperCase().includes('UNIQUE');
        const opts: string[] = [`type: ${mType}`];
        if (required) opts.push('required: true');
        if (unique) opts.push('unique: true');
        return `  ${fieldName}: { ${opts.join(', ')} }`;
      });
    out += fields.join(',\n');
    out += `\n}, { timestamps: true });\n`;
    out += `const ${modelName} = mongoose.model('${modelName}', ${toCamelCase(table.table)}Schema);\n`;
  }

  const exportNames = bp.schema.map((t) => toPascalCase(t.table));
  out += `\nmodule.exports = { ${exportNames.join(', ')} };\n`;
  return out;
}

/** Detect whether a string looks like raw SQL (vs Mongoose/JS). */
function looksLikeSql(code: string): boolean {
  return /\bCREATE\s+TABLE\b|\bALTER\s+TABLE\b|\bINSERT\s+INTO\b/i.test(code);
}

export function streamScaffoldZip(bp: Blueprint, res: Response): void {
  const appSlug = toKebabCase(bp.appName);
  const isMongo = bp.architecture.database.toLowerCase().includes('mongo');

  res.setHeader('Content-Type', 'application/zip');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename="${appSlug}-scaffold.zip"`
  );

  const archive = archiver('zip', { zlib: { level: 6 } });

  archive.on('error', (err) => {
    console.error('[Scaffold] Archive error:', err);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Failed to generate project ZIP' });
    } else {
      res.destroy(); // Destroy socket to signal corrupted/partial download
    }
  });

  archive.pipe(res);

  // ─── Root files ────────────────────────────────────────
  archive.append(generateRootPackageJson(bp), { name: 'package.json' });
  archive.append(generateDockerCompose(bp), { name: 'docker-compose.yml' });
  archive.append(generateReadme(bp), { name: 'README.md' });
  archive.append(generateGitignore(), { name: '.gitignore' });

  // ─── Backend ───────────────────────────────────────────
  archive.append(generateBackendPackageJson(bp), { name: 'backend/package.json' });
  archive.append(generateBackendTsconfig(), { name: 'backend/tsconfig.json' });
  // Env example
  archive.append(generateEnvExample(bp), { name: 'backend/.env.example' });
  if (!isMongo) {
    archive.append(generatePrismaSchema(bp), { name: 'backend/prisma/schema.prisma' });
  }
  archive.append(generateBackendIndex(bp), { name: 'backend/src/index.ts' });
  archive.append(
    bp.code.backend && bp.code.backend.trim() ? bp.code.backend : generateBackendApp(bp),
    { name: 'backend/src/app.ts' }
  );

  // Route files — one per resource
  const resources = new Set<string>();
  for (const ep of bp.endpoints) {
    const parts = ep.path.split('/').filter(Boolean);
    if (parts.length >= 2) resources.add(parts[1]);
  }
  for (const resource of resources) {
    archive.append(generateRouteFile(resource, bp.endpoints), {
      name: `backend/src/routes/${resource}.ts`,
    });
  }

  // ─── Frontend ──────────────────────────────────────────
  archive.append(generateFrontendPackageJson(bp), { name: 'frontend/package.json' });
  archive.append(
    bp.code.frontend && bp.code.frontend.trim() ? bp.code.frontend : generateFrontendApp(bp),
    { name: 'frontend/src/App.tsx' }
  );
  archive.append(
    `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App';\nimport './index.css';\n\nReactDOM.createRoot(document.getElementById('root')!).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>\n);\n`,
    { name: 'frontend/src/main.tsx' }
  );
  archive.append('@tailwind base;\n@tailwind components;\n@tailwind utilities;\n', {
    name: 'frontend/src/index.css',
  });
  archive.append(generateApiClient(bp), { name: 'frontend/src/lib/api.ts' });

  // Page files — one per screen
  for (const screen of bp.screens) {
    const name = toPascalCase(screen.name.replace(/[^a-zA-Z0-9]/g, ''));
    archive.append(generateFrontendPage(screen), {
      name: `frontend/src/pages/${name}Page.tsx`,
    });
  }

  // Index HTML
  archive.append(
    `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8" />\n  <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n  <title>${bp.appName}</title>\n</head>\n<body>\n  <div id="root"></div>\n  <script type="module" src="/src/main.tsx"></script>\n</body>\n</html>\n`,
    { name: 'frontend/index.html' }
  );

  // DB Schema File
  if (isMongo) {
    // For MongoDB, emit Mongoose models. Use the AI-provided code.sql ONLY if
    // it actually contains JS/Mongoose (not raw SQL and not empty); otherwise
    // generate models from bp.schema so schema.js is never blank.
    const aiCode = (bp.code.sql || '').trim();
    const useAiCode = aiCode.length > 0 && !looksLikeSql(aiCode);
    const mongoSchema = useAiCode ? aiCode : generateMongooseSchema(bp);
    archive.append(mongoSchema, { name: 'backend/schema.js' });
  } else {
    const sql = (bp.code.sql || '').trim();
    archive.append(sql.length > 0 ? sql : '-- No SQL schema generated', {
      name: 'backend/schema.sql',
    });
  }

  archive.finalize();
}

/**
 * Build a flat dictionary of all scaffold files (path → content).
 * This is the same set of files written to the ZIP archive, but returned
 * as a Record so the frontend Code Studio can display them inline.
 */
export function generateMonorepoFiles(bp: Blueprint): Record<string, string> {
  const files: Record<string, string> = {};
  const isMongo = bp.architecture.database.toLowerCase().includes('mongo');

  // ─── Root files ────────────────────────────────────────
  files['package.json'] = generateRootPackageJson(bp);
  files['docker-compose.yml'] = generateDockerCompose(bp);
  files['README.md'] = generateReadme(bp);
  files['.gitignore'] = generateGitignore();

  // ─── Backend ───────────────────────────────────────────
  files['backend/package.json'] = generateBackendPackageJson(bp);
  files['backend/tsconfig.json'] = generateBackendTsconfig();
  files['backend/.env.example'] = generateEnvExample(bp);
  if (!isMongo) {
    files['backend/prisma/schema.prisma'] = generatePrismaSchema(bp);
  }
  files['backend/src/index.ts'] = generateBackendIndex(bp);
  files['backend/src/app.ts'] = bp.code.backend && bp.code.backend.trim() ? bp.code.backend : generateBackendApp(bp);

  // Route files — one per resource
  const resources = new Set<string>();
  for (const ep of bp.endpoints) {
    const parts = ep.path.split('/').filter(Boolean);
    if (parts.length >= 2) resources.add(parts[1]);
  }
  for (const resource of resources) {
    files[`backend/src/routes/${resource}.ts`] = generateRouteFile(resource, bp.endpoints);
  }

  // ─── Frontend ──────────────────────────────────────────
  files['frontend/package.json'] = generateFrontendPackageJson(bp);
  files['frontend/src/App.tsx'] = bp.code.frontend && bp.code.frontend.trim() ? bp.code.frontend : generateFrontendApp(bp);
  files['frontend/src/main.tsx'] = `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App';\nimport './index.css';\n\nReactDOM.createRoot(document.getElementById('root')!).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>\n);\n`;
  files['frontend/src/index.css'] = '@tailwind base;\n@tailwind components;\n@tailwind utilities;\n';
  files['frontend/src/lib/api.ts'] = generateApiClient(bp);

  // Page files — one per screen
  for (const screen of bp.screens) {
    const name = toPascalCase(screen.name.replace(/[^a-zA-Z0-9]/g, ''));
    files[`frontend/src/pages/${name}Page.tsx`] = generateFrontendPage(screen);
  }

  // Index HTML
  files['frontend/index.html'] = `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8" />\n  <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n  <title>${bp.appName}</title>\n</head>\n<body>\n  <div id="root"></div>\n  <script type="module" src="/src/main.tsx"></script>\n</body>\n</html>\n`;

  // DB Schema File
  if (isMongo) {
    const aiCode = (bp.code.sql || '').trim();
    const useAiCode = aiCode.length > 0 && !looksLikeSql(aiCode);
    files['backend/schema.js'] = useAiCode ? aiCode : generateMongooseSchema(bp);
  } else {
    const sql = (bp.code.sql || '').trim();
    files['backend/schema.sql'] = sql.length > 0 ? sql : '-- No SQL schema generated';
  }

  return files;
}

